<a href="https://colab.research.google.com/github/shreyabhatt025/Python-Libraries-/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#creating array from python list
a=np.array([[1,2],[3,4]])
print(a)
b=np.array([[5,6],[7,8]])
a+b


[[1 2]
 [3 4]]


array([[ 6,  8],
       [10, 12]])

In [ ]:
filled_Array=np.full((2,2),7)
print(filled_Array)

[[7 7]
 [7 7]]


In [ ]:
#identity matrix
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#creating sequnces of number in numpy
#arange function ( start,stop,step)
arr=np.arange(1,10,2)
print(arr) #it returns a numpy array


[1 3 5 7 9]


In [ ]:
#When workinh with multi dimension array
#SHAPE - return array (row,column)
import numpy as np
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d.shape)

#SIZE- total no of elements in array
print(arr_2d.size)

#ndim - use to check no of dimension , n stands for number , dim stands for dimension
print(arr_2d.ndim)

#d type - return data type of array
print(arr_2d.dtype)



(2, 3)
6
2
int64


In [ ]:
#astype()- use to convert data type of array
arr=np.array([1.2,3.4,5.6])
print(arr.dtype)
int_arr=arr.astype(int)
print(int_arr)
print(int_arr.dtype)


float64
[1 3 5]
int64


In [ ]:
#AGGREGATION FUNCTION
a=np.array([[10,20,30,40,50]])
print(np.sum(a))
print(np.mean(a))
print(np.min(a))
print(np.max(a))
print(np.std(a))
print(np.var(a))



150
30.0
10
50
14.142135623730951
200.0


In [ ]:
## Numpy use 0 base indexing
#INDEXING - Indexing a NumPy array means accessing the elements of the NumPy array at the given index.

#There are two types of indexing in NumPy: basic indexing and advanced indexing.

import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[4])
print(arr[-1])
#sliicng
print(arr[1:5])
print(arr[:4])
print(arr[::-1]) # reverse array without loop



50
50
[20 30 40 50]
[10 20 30 40]
[50 40 30 20 10]
