<a href="https://colab.research.google.com/github/shreyabhatt025/StayBase/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
#creating array from python list
a=np.array([[1,2],[3,4]])
print(a)
b=np.array([[5,6],[7,8]])
a+b


[[1 2]
 [3 4]]


array([[ 6,  8],
       [10, 12]])

In [5]:
filled_Array=np.full((2,2),7)
print(filled_Array)

[[7 7]
 [7 7]]


In [6]:
#creating sequnces of number in numpy
#arange function ( start,stop,step)
arr=np.arange(1,10,2)
print(arr) #it returns a numpy array


[1 3 5 7 9]
